### PR TITLE
Base Template - draft #3 

### PR DESCRIPTION
**Pull request by viraji**
> __ALL Pull-Requests require an associated [Issue](https://github.com/thegooddocsproject/templates/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) as documented in [How to contribute](https://github.com/thegooddocsproject/templates/blob/master/CONTRIBUTING.md#contributing).__

## Purpose / why

> _This PR is based on review comments of https://github.com/thegooddocsproject/incubator/pull/14._

## What changes were made?

> _**Changes to**_ :
- base-template.md
- about-base-template.md

## Verification

> _**Please help** - I have tried to incorporate all review comments to PR #14 as best as I could. But I feel that we can revise and improve further on the " essential elements of your template" section - your suggestions/comments are much appreciated._

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Are issues linked correctly?
* [ ] Is this PR labeled correctly?
* [ ] If template updates: do they align with [developers.google.com/style/](https://developers.google.com/style/)?
* [ ] Did the PR receive at least one :+1: and no :-1: from core-maintainers?
* [ ] On merging, did you complete the merge using [keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue)?
* [ ] On merging, did you add any applicable notes to a [draft release](https://github.com/thegooddocsproject/templates/releases) and link to this PR?

### CODE REVIEW

**Comment by viraji** [comment]
This PR consists of review comments from and improvements to #14.

**Comment by barbaricyawps** [comment]
**Question:** I need some more context for this template in order to do a full review. Since the only link you've included is to a prior PR (not an issue) or other conversations, I'm missing some context (and that's probably on me). Btw, is this the issue you're technically trying to resolve with this PR? https://github.com/thegooddocsproject/templates/issues/94

Is this template intended to be primarily used by GDP contributors who are creating a new template? So, for example, the use case is that a GDP contributor who wants to submit a new template will pull your template and use it as their base draft?

And then is the secondary audience an open source project that wants to just provide a base template for a new future templates that includes the core "wrapper" content that it should contain?

If I can get some more context here, I'll jump in and do a more directed review. Thanks!

**Comment by camerons** [comment]
I feel that @viraji has made improvements to the base templates as it stands, and as such we, should accept this pull request onto the main branch (of our incubator repository). I'll give a day or two for others to comment, and if there are no objections, I will merge. (Feel free to nudge me if I forget.)

I have a lot more thoughts on how I think we can improve the base template. And it will probably be easiest if I provide this feedback in my own I separate pull request, which I can do after accepting @viraji 's pull request.

Answering @barbaricyawps, the target audience for the base template is a template author.

This is confusing to get our heads around:
* The base template needs to explain:
  * How a template author should write writing instructions for:
    * The end doc author.

Both the about-base-template.md and base-template.md should be templates themselves which are forked to create a base-xxx-template.md and xxx-template.md. I feel these documents should have embedded writing instructions inside them. Something like:

{This section is optional. If included, it should cover the provide the following guidance ...}

I'm moving toward the idea that we maybe need three documents:
* Two templates: about-base-template.md and base-template.md 
* And one how-to-fill-out-these-docs.md

**Comment by aidanatwork** [comment]
I think this is a good start. I have a lot of suggestions for how we might be able to potentially change the copy here, but I think that would be done best as new issues or PRs raised on the files once they are merged into the Incubator. I think we should go ahead and merge this PR and then discuss further.

**Comment by viraji** [comment]
Thank you all for your reviews, feedback and suggestions.
@Alyssa, sorry I should've been clearer about the task in the PR
description, but I see that @Cameron Shorter <cameron.shorter@gmail.com>
has already answered your question.

Thanks @Cameron Shorter <cameron.shorter@gmail.com> for your suggestion,
let's merge this and work on further improvements.

/Viraji.

**Comment by camerons** [comment]
I've merged based on my prior comments. This is a good start to base templates from which we can build within the incubator repository.

**Pull request merged**
